SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `popcorn`.`pn_users`
CHANGE COLUMN `type` `type` INT(2) NOT NULL DEFAULT 1
COMMENT '1 - user\n2 - moderator\n3 - editor\n4 - admin',
CHANGE COLUMN `avatar` `avatar` INT(11) NOT NULL DEFAULT 0,
ADD COLUMN `createTime` INT(11) NOT NULL DEFAULT 0
AFTER `lastVisit`;

ALTER TABLE `popcorn`.`pn_users_info`
DROP COLUMN `subscribeSentDate`,
CHANGE COLUMN `sex` `sex` INT(1) NOT NULL DEFAULT 0
COMMENT '0 - unknown\n1 - male\n2 - female',
CHANGE COLUMN `countryId` `countryId` INT(11) NOT NULL DEFAULT 0,
CHANGE COLUMN `cityId` `cityId` INT(11) NOT NULL DEFAULT 0,
CHANGE COLUMN `married` `married` INT(1) NOT NULL DEFAULT 0
COMMENT '0 - unknown\n1 - single\n2 - married';


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
