<?php
/**
 * Created by PhpStorm.
 * User: Aleksey Kolyadin
 * Date: 19.02.14
 * Time: 13:46
 */

namespace popcorn\cli\helpers;


class BBHelper {

	static public function convertOldBB($string) {

		$smiles = [
			'[china]'              => '',
			'[fight]'              => ':punch:',
			'[abuse]'              => '',
			'[indian]'             => '',
			'[lamo]'               => '',
			'[admin]'              => '',
			'[ufo]'                => '',
			'[batman]'             => '',
			'[shooter]'            => '',
			'[Smile]'              => ':smile:',
			'[Indignation]'        => '',
			'[Perfectly]'          => ':thumbsup:',
			'[Super]'              => ':thumbsup:',
			'[Unsure]'             => '',
			'[Wink]'               => ':wink:',
			'[Yes]'                => ':thumbsup:',
			'[Tears]'              => '',
			'[Idea]'               => '',
			'[Banter]'             => '',
			'[Sad]'                => '',
			'[Exclaim]'            => '',
			'[Fun]'                => ':laughing:',
			'[Confusion]'          => ':flushed:',
			'[Tease]'              => '',
			'[Tongue]'             => '',
			'[Arrow]'              => '',
			'[Surprise]'           => '',
			'[Sly]'                => '',
			'[Shock]'              => ':open_mouth:',
			'[Sorrow]'             => '',
			'[Angry ]'             => ':rage:',
			'[Grumbler]'           => '',
			'[Dreamer]'            => ':relieved:',
			'[Side-splitting]'     => ':laughing:',
			'[Question]'           => '',
			'[Plus]'               => '',
			'[No]'                 => ':thumbsdown:',
			'[Minus]'              => '',
			'[Peace]'              => '',
			'[Secret]'             => '',
			'[Severe]'             => '',
			'[Obstinate]'          => ':triumph:',
			'[Relaxation]'         => ':sunglasses:',
			'[Dance]'              => '',
			'[Fury]'               => '',
			'[Bye]'                => '',
			'[Grin]'               => ':sunglasses:',
			'[Sob]'                => ':sob:',
			'[Booby]'              => ':hushed:',
			'[Grief]'              => '',
			'[Puzzle]'             => ':confused:',
			'[Merry]'              => ':laughing:',
			'[Satisfied]'          => ':satisfied:',
			'[Redden]'             => ':flushed:',
			'[Blush]'              => '',
			'[Discomfiture]'       => ':confused:',
			'[Mad]'                => ':smiley:',
			'[Dribble]'            => ':stuck_out_tongue:',
			'[censored]'           => '',
			'[jester]'             => '',
			'[beer1]'              => '',
			'[dirty_trick]'        => '',
			'[transformer]'        => '',
			'[read]'               => '',
			'[boxer]'              => '',
			'[vanishing]'          => '',
			'[bravo]'              => ':clap:',
			'[invalid]'            => '',
			'[devil]'              => ':smiling_imp:',
			'[injection]'          => '',
			'[athlene]'            => '',
			'[wall]'               => '',
			'[fourth]'             => ':revolving_hearts:',
			'[judge]'              => '',
			'[help]'               => '',
			'[in_love]'            => ':heart_eyes:',
			'[dancer]'             => '',
			'[lamp]'               => '',
			'[mobile]'             => '',
			'[no-no]'              => '',
			'[God]'                => '',
			'[yo]'                 => ':v:',
			'[congratulate]'       => ':cake:',
			'[beer]'               => '',
			'[crazy]'              => ':alien:',
			'[piska]'              => '',
			'[acute]'              => '',
			'[aggressive]'         => '',
			'[agree]'              => '',
			'[air_kiss]'           => '',
			'[alcoholic]'          => '',
			'[bad]'                => ':cold_sweat:',
			'[beee]'               => '',
			'[black_eye]'          => '',
			'[blum2]'              => '',
			'[blush]'              => ':flushed:',
			'[blush2]'             => '',
			'[boast]'              => '',
			'[boredom]'            => '',
			'[clapping]'           => '',
			'[cray]'               => '',
			'[crazy_pilot]'        => '',
			'[dance]'              => '',
			'[dance3]'             => '',
			'[dance4]'             => '',
			'[dash2]'              => '',
			'[dash3]'              => '',
			'[declare]'            => '',
			'[derisive]'           => '',
			'[dirol]'              => '',
			'[dntknw]'             => '',
			'[don-t_mention]'      => '',
			'[download]'           => '',
			'[drag]'               => '',
			'[drinks]'             => '',
			'[focus]'              => '',
			'[fool]'               => '',
			'[friends]'            => ':two_women_holding_hands:',
			'[gamer1]'             => '',
			'[gamer3]'             => '',
			'[gamer4]'             => '',
			'[girl_crazy]'         => '',
			'[girl_hospital]'      => '',
			'[girl_wacko]'         => '',
			'[good]'               => '',
			'[good2]'              => ':thumbsup:',
			'[grin]'               => '',
			'[hang3]'              => '',
			'[heat]'               => '',
			'[hunter]'             => '',
			'[i-m_so_happy]'       => '',
			'[ireful1]'            => '',
			'[laugh3]'             => ':laughing:',
			'[lazy]'               => '',
			'[lazy2]'              => '',
			'[locomotive]'         => '',
			'[mail1]'              => '',
			'[man_in_love]'        => ':heart_eyes:',
			'[mda]'                => '',
			'[meeting]'            => '',
			'[mosking]'            => ':smile:',
			'[nea]'                => '',
			'[negative]'           => '',
			'[no2]'                => '',
			'[not_i]'              => '',
			'[ok]'                 => '',
			'[on_the_quiet]'       => '',
			'[pardon]'             => '',
			'[party]'              => '',
			'[pilot]'              => '',
			'[pleasantry]'         => '',
			'[polling]'            => '',
			'[popcorm1]'           => '',
			'[prankster2]'         => '',
			'[preved]'             => '',
			'[punish]'             => '',
			'[resent]'             => '',
			'[rofl]'               => ':laughing:',
			'[russian_roulette]'   => '',
			'[sad]'                => '',
			'[sarcastic]'          => ':laughing:',
			'[sarcastic_blum]'     => ':stuck_out_tongue_closed_eyes:',
			'[scare]'              => '',
			'[scare2]'             => '',
			'[sclerosis]'          => '',
			'[scratch_one-s_head]' => '',
			'[search]'             => '',
			'[secret]'             => '',
			'[shout]'              => '',
			'[smile3]'             => '',
			'[smoke]'              => ':sunglasses:',
			'[snooks]'             => '',
			'[sorry]'              => '',
			'[sorry2]'             => '',
			'[stink]'              => '',
			'[stinker]'            => '',
			'[stop]'               => '',
			'[suicide2]'           => '',
			'[superstition]'       => '',
			'[swoon]'              => '',
			'[swoon2]'             => '',
			'[take_example]'       => '',
			'[taunt]'              => '',
			'[tease]'              => ':stuck_out_tongue_closed_eyes:',
			'[telephone]'          => '',
			'[thank_you]'          => '',
			'[this]'               => '',
			'[threaten]'           => '',
			'[to_become_senile]'   => '',
			'[to_clue]'            => '',
			'[to_pick_ones_nose]'  => '',
			'[to_pick_ones_nose2]' => '',
			'[to_take_umbrage]'    => '',
			'[tongue]'             => '',
			'[umnik]'              => '',
			'[victory]'            => '',
			'[wacko]'              => '',
			'[whistle3]'           => '',
			'[wink3]'              => '',
			'[yahoo]'              => ':stuck_out_tongue_winking_eye:',
			'[yes2]'               => '',
			'[yes3]'               => '',
			'[yu]'                 => '',
		];

		$string = strtr($string, $smiles);


		$string = preg_replace('!\[b\].*\[\/b\]!is','',$string);
		$string = preg_replace('!\[quote\].*\[\/quote\]!is','',$string);
		$string = preg_replace('!\[quote\].*\[\/quote!is','',$string);
		$string = preg_replace('!\[quote\].*\[\/qu!is','',$string);

		$string = preg_replace('#\[[^\]]+\]#s','',$string);

		$string = strtr($string,[
			'[/quote' => '',
			'[/qu' => ''
		]);

		return $string;
	}

}